### ISSUE TITLE
Interpret bit-wise data in .bmp images

### ISSUE THREAD

**Issue by jchackim** [Breyno17/Aurora#2]
I don't understand how to do this.

**Comment by Breyno17** [comment]
I do

**Comment by jchackim** [comment]
Great! Tell me how and close/comment the issue.

**Comment by Breyno17** [comment]
I solved the issue

**Comment by jchackim** [comment]
I'm re-opening the issue, @Breyno17 ya poopy head. In order to test the email stuff 👯‍♂️

**Comment by jchackim** [comment]
Glad you got an email. Hasta!
